### ISSUE TITLE
Some keyword definitions and the proof of Even Numbers

### ISSUE THREAD

**Issue by ZHANGHE24** [awslabs/s2n-bignum#3]
First of all, I must thank you once again for your help to me last time. But I'm running into some new problems now.
1. I still cannot find some keyword definitions.
     For example:
          Comb, Const
     I guess they may be defined in the ocaml, but I only can find many place they used but not have any definitions.
     If you know some material about them, please give me some guidance, thanks.

2.  Some problem about code.
     1)
      In the x86/general/bignum_even.S ([https://github.com/awslabs/s2n-bignum/blob/main/x86/generic/bignum_even.S](url)) and x86/proofs/bignum_even.ml ([https://github.com/awslabs/s2n-bignum/blob/main/x86/proofs/bignum_even.ml](url)), 
      I find you only judge whether the value of the first address of the array is an even number in the assembly code.(I know it is enough.) However, in the proof of bignum_even, you calculate the sum of the array to get the whole big_num, and then you use it to prove the correctness of the even function. If what I said above is correct, why not only prove that the value of the first address of array is even in .ml file?
      If I made mistakes, please forgive me, thanks.
     2)
     Line 74 in the bignum_even.ml [https://github.com/awslabs/s2n-bignum/blob/main/x86/proofs/bignum_even.ml](url)
     `read RSP s = word_add stackpointer (word 8) /\`
     "word 8" means 8 bytes? 
     rsp + 8 <=> Recovered one address spaces(the return address)? (because x86_64 has a 64-bit address?)
     
          ------------------ <- RSP (after ret)
           return address
          ------------------  <- stackpointer 
          and stackpointer  + 8 = RSP
     Is it right?   or word 8 = 1 byte (the length of "ret")?
     3) 
     Line 55 in the bignum_even.ml [https://github.com/awslabs/s2n-bignum/blob/main/x86/proofs/bignum_even.ml](url)
     `X86_SIM_TAC BIGNUM_EVEN_EXEC (1--5);`
     What does "(1--5)" mean? I only know it represents "[1,2,3,4,5]", but I cannot understand what this code means.
     Could you give me an explanation or example? please.
     4)
      Because of my abilities, I can't write assembly code directly. Therefore, I want to ask you if I write c code and compile it into assembly code, if I can do formal verification the way you do it.(I will use the verified llvm to do the compilation.)
      Is there a difference between them?

If you have free time, please help me, thank you again. (* ^ ω ^)

**Comment by jargh** [comment]
A few answers which I hope clarify most of these things:

1. These constructs are from the HOL Light prover, which is the additional layer on top of OCaml in which the proofs are conducted. More here https://www.cl.cam.ac.uk/~jrh13/hol-light/. Also the "m--n" construct in question 2 is defined there (it means a range of integers from m to n, e.g. 1--4 being [1;2;3;4]).

2. Your comment about lowest word versus whole thing is quite true. But in general the goal is to state mathematical results in their "natural" abstract setting, and the fact that you only need to look at the lowest word is considered an implementation optimization. Generally the whole goal here is to make the specifications transparently correspond to their normal mathematical sense, otherwise there is a danger you could be hiding bugs by making the same error in the specification as in the code itself.

In principle the verification method is applicable to machine code generated in any way whatsoever. In practice it can be hard to understand what the compiler is doing well enough when you see its end results, and since proofs are not usually fully automatic, you do want a clear understanding to generate a formal proof. All of the code in this repo is hand-written, but I have tried one or two trivial experiments with code fragments generated by gcc.
